using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace ProjekatPlatforme.Coach
{
    /// <summary>
    /// Interaction logic for CoachReviewWindow.xaml
    /// </summary>
    public partial class CoachReviewWindow : Window
    {
        ICollectionView view;
        public CoachReviewWindow()
        {
            InitializeComponent();
            view = CollectionViewSource.GetDefaultView(Application.Instance.Coaches);
            dataGrid.ItemsSource = view;
            dataGrid.IsSynchronizedWithCurrentItem = true;
        }

        private void dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dataGrid.Columns[4].Visibility = System.Windows.Visibility.Hidden;
        }

        private void ButtonBack(object sender, RoutedEventArgs e)
        {
            MainWindow mainWin = new MainWindow();
            this.Visibility = Visibility.Hidden;
            mainWin.Show();
        }

        private void ButtonSearch(object sender, RoutedEventArgs e)
        {
            SearchCoachUnReg src = new SearchCoachUnReg();
            this.Visibility = Visibility.Hidden;
            src.Show();
        }
    }
}
