using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace ProjekatPlatforme.Administrator
{
    /// <summary>
    /// Interaction logic for BeginnerReview.xaml
    /// </summary>
    public partial class BeginnerReview : Window
    {

        ICollectionView view;

        public BeginnerReview()
        {
            InitializeComponent();
            view = CollectionViewSource.GetDefaultView(Application.Instance.Beginners);
            dataGrid.ItemsSource = view;
            dataGrid.IsSynchronizedWithCurrentItem = true;
            Application.Instance.Beginners.Clear();
            Users.Beginner.LoadBeginners();
        }
        private void dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dataGrid.Columns[4].Visibility = System.Windows.Visibility.Hidden;
        }

        private void ButtonBack(object sender, RoutedEventArgs e)
        {
            AdminMenu adminMenuWin = new AdminMenu();
            this.Visibility = Visibility.Hidden;
            adminMenuWin.Show();
        }

        private void CreateBtn(object sender, RoutedEventArgs e)
        {
            Users.Beginner newBeginner = new Users.Beginner();
            Address.Address newAddress = new Address.Address();
            Beginner.AddBeginner beginner = new Beginner.AddBeginner(newBeginner, newAddress);
            this.Visibility = Visibility.Hidden;
            beginner.ShowDialog();
        }

        private void DeleteBtn(object sender, RoutedEventArgs e)
        {
            Users.Beginner selectedBeginner = view.CurrentItem as Users.Beginner;

            if(selectedBeginner != null)
            {
                string firstNameSelected = selectedBeginner.FirstName;
                long jmbgSelected = selectedBeginner.Jmbg;
                int addressSelected = selectedBeginner.IDAddress;

                if (MessageBox.Show("Are you sure you want to delete the beginner: " + firstNameSelected, "Confirm option",
                    MessageBoxButton.YesNo) == MessageBoxResult.Yes)
                {
                    Application.Instance.Beginners.Remove(selectedBeginner);
                    Users.Beginner.DeleteBeginner(jmbgSelected);

                    Address.Address.DeleteAddressAdmin(addressSelected);
                }
            }
            else
            {
                MessageBox.Show("Select beginner!");
            }



        }

        private void updateBtn_Click(object sender, RoutedEventArgs e)
        {
            Users.Beginner selectedBeginner = view.CurrentItem as Users.Beginner;

            if(selectedBeginner != null)
            {
                long selectedJmbg = selectedBeginner.Jmbg;
                string selectedFirstName = selectedBeginner.FirstName;
                string selectedLastName = selectedBeginner.LastName;
                string selectedPassword = selectedBeginner.Password;
                string selectedEmail = selectedBeginner.Email;
                int slectedAddressId = selectedBeginner.IDAddress;
                Users.EGender selectedGender = selectedBeginner.Gender;

                Beginner.BeginnerEditWindow beg = new Beginner.BeginnerEditWindow(selectedJmbg, selectedFirstName, selectedLastName, selectedPassword, selectedEmail, slectedAddressId, selectedGender);
                this.Visibility = Visibility.Hidden;
                beg.ShowDialog();
            }
            else
            {
                MessageBox.Show("Please select beginner");
            }

        }


    }
}
