using ProjekatPlatforme.Coach;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace ProjekatPlatforme.Administrator
{
    /// <summary>
    /// Interaction logic for CoachReview.xaml
    /// </summary>
    public partial class CoachReview : Window
    {
        ICollectionView view;
        public CoachReview()
        {
            InitializeComponent();
            view = CollectionViewSource.GetDefaultView(Application.Instance.Coaches);
            dataGrid.ItemsSource = view;
            dataGrid.IsSynchronizedWithCurrentItem = true;
            Application.Instance.Coaches.Clear();
            Users.Coach.LoadCoaches();
        }

        private void dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dataGrid.Columns[4].Visibility = System.Windows.Visibility.Hidden;
        }

        private void ButtonBack(object sender, RoutedEventArgs e)
        {
            AdminMenu adminMenuWin = new AdminMenu();
            this.Visibility = Visibility.Hidden;
            adminMenuWin.Show();
        }

        private void CreateBtn(object sender, RoutedEventArgs e)
        {
            Users.Coach newCoach = new Users.Coach();
            Address.Address newAddress = new Address.Address();
            CoachAddWindow cew = new CoachAddWindow(newCoach, newAddress);
            this.Visibility = Visibility.Hidden;
            cew.ShowDialog();
        }

        private void DeleteBtn(object sender, RoutedEventArgs e)
        {
            Users.Coach selectedCoach = view.CurrentItem as Users.Coach;

            if(selectedCoach != null)
            {
                string firstNameSelected = selectedCoach.FirstName;
                long jmbgSelected = selectedCoach.Jmbg;
                int addressSelected = selectedCoach.IDAddress;

                if (MessageBox.Show("Are you sure you want to delete the coach: " + firstNameSelected, "Confirm option",
                    MessageBoxButton.YesNo) == MessageBoxResult.Yes)
                {
                    Application.Instance.Coaches.Remove(selectedCoach);
                    Users.Coach.DeleteCoach(jmbgSelected);

                    Address.Address.DeleteAddressAdmin(addressSelected);
                }
            }
            else
            {
                MessageBox.Show("Please select coach!");
            }


        }


        private void UpdateBtn(object sender, RoutedEventArgs e)
        {
          
            Users.Coach selectedCoach = view.CurrentItem as Users.Coach;
            if(selectedCoach != null)
            {
                long selectedJmbg = selectedCoach.Jmbg;
                string selectedFirstName = selectedCoach.FirstName;
                string selectedLastName = selectedCoach.LastName;
                string selectedPassword = selectedCoach.Password;
                string selectedEmail = selectedCoach.Email;
                int slectedAddressId = selectedCoach.IDAddress;
                Users.EGender selectedGender = selectedCoach.Gender;

                CoachEditWindow cew = new CoachEditWindow(selectedJmbg, selectedFirstName, selectedLastName, selectedPassword, selectedEmail, slectedAddressId, selectedGender);
                this.Visibility = Visibility.Hidden;
                cew.ShowDialog();
            }
            else
            {
                MessageBox.Show("Please select coach");
            }

        }


    }
}
